### ISSUE TITLE
Access to the full dataset

### ISSUE THREAD

**Issue by feralvam** [eliorsulem/HSplit-corpus#1]
Hello,
Thanks for this data. From the paper, I understand that all the test set of the TurkCorpus (359 sentences) were simplified (third page, second paragraph). However, in the repo only 70 are available (the ones used for the human evaluation). Is it possible to get the full HSplit with the 359 sentences?

**Comment by eliorsulem** [comment]
Hi,

Thanks for the comment. The whole dataset is now available in the HSplit folder. 
The first 70 sentences used for the human evaluation also appear in the HSplit_human_evaluation folder.

**Comment by feralvam** [comment]
Brilliant! Thanks.
